/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as SplatImport } from "./routes/$"
import { Route as DashboardIndexImport } from "./routes/dashboard/index"
import { Route as DashboardSignUpImport } from "./routes/dashboard/sign-up"
import { Route as DashboardSignInImport } from "./routes/dashboard/sign-in"
import { Route as DashboardSettingsImport } from "./routes/dashboard/settings"
import { Route as DashboardSplatImport } from "./routes/dashboard/$"
import { Route as DashboardUsersIndexImport } from "./routes/dashboard/users/index"
import { Route as DashboardUsersUseridImport } from "./routes/dashboard/users/$user_id"

// Create/Update Routes

const SplatRoute = SplatImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => rootRoute,
} as any)

const DashboardSignUpRoute = DashboardSignUpImport.update({
  id: "/dashboard/sign-up",
  path: "/dashboard/sign-up",
  getParentRoute: () => rootRoute,
} as any)

const DashboardSignInRoute = DashboardSignInImport.update({
  id: "/dashboard/sign-in",
  path: "/dashboard/sign-in",
  getParentRoute: () => rootRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: "/dashboard/settings",
  path: "/dashboard/settings",
  getParentRoute: () => rootRoute,
} as any)

const DashboardSplatRoute = DashboardSplatImport.update({
  id: "/dashboard/$",
  path: "/dashboard/$",
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersIndexRoute = DashboardUsersIndexImport.update({
  id: "/dashboard/users/",
  path: "/dashboard/users/",
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersUseridRoute = DashboardUsersUseridImport.update({
  id: "/dashboard/users/$user_id",
  path: "/dashboard/users/$user_id",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/$": {
      id: "/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    "/dashboard/$": {
      id: "/dashboard/$"
      path: "/dashboard/$"
      fullPath: "/dashboard/$"
      preLoaderRoute: typeof DashboardSplatImport
      parentRoute: typeof rootRoute
    }
    "/dashboard/settings": {
      id: "/dashboard/settings"
      path: "/dashboard/settings"
      fullPath: "/dashboard/settings"
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof rootRoute
    }
    "/dashboard/sign-in": {
      id: "/dashboard/sign-in"
      path: "/dashboard/sign-in"
      fullPath: "/dashboard/sign-in"
      preLoaderRoute: typeof DashboardSignInImport
      parentRoute: typeof rootRoute
    }
    "/dashboard/sign-up": {
      id: "/dashboard/sign-up"
      path: "/dashboard/sign-up"
      fullPath: "/dashboard/sign-up"
      preLoaderRoute: typeof DashboardSignUpImport
      parentRoute: typeof rootRoute
    }
    "/dashboard/": {
      id: "/dashboard/"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    "/dashboard/users/$user_id": {
      id: "/dashboard/users/$user_id"
      path: "/dashboard/users/$user_id"
      fullPath: "/dashboard/users/$user_id"
      preLoaderRoute: typeof DashboardUsersUseridImport
      parentRoute: typeof rootRoute
    }
    "/dashboard/users/": {
      id: "/dashboard/users/"
      path: "/dashboard/users"
      fullPath: "/dashboard/users"
      preLoaderRoute: typeof DashboardUsersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/$": typeof SplatRoute
  "/dashboard/$": typeof DashboardSplatRoute
  "/dashboard/settings": typeof DashboardSettingsRoute
  "/dashboard/sign-in": typeof DashboardSignInRoute
  "/dashboard/sign-up": typeof DashboardSignUpRoute
  "/dashboard": typeof DashboardIndexRoute
  "/dashboard/users/$user_id": typeof DashboardUsersUseridRoute
  "/dashboard/users": typeof DashboardUsersIndexRoute
}

export interface FileRoutesByTo {
  "/$": typeof SplatRoute
  "/dashboard/$": typeof DashboardSplatRoute
  "/dashboard/settings": typeof DashboardSettingsRoute
  "/dashboard/sign-in": typeof DashboardSignInRoute
  "/dashboard/sign-up": typeof DashboardSignUpRoute
  "/dashboard": typeof DashboardIndexRoute
  "/dashboard/users/$user_id": typeof DashboardUsersUseridRoute
  "/dashboard/users": typeof DashboardUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/$": typeof SplatRoute
  "/dashboard/$": typeof DashboardSplatRoute
  "/dashboard/settings": typeof DashboardSettingsRoute
  "/dashboard/sign-in": typeof DashboardSignInRoute
  "/dashboard/sign-up": typeof DashboardSignUpRoute
  "/dashboard/": typeof DashboardIndexRoute
  "/dashboard/users/$user_id": typeof DashboardUsersUseridRoute
  "/dashboard/users/": typeof DashboardUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/$"
    | "/dashboard/$"
    | "/dashboard/settings"
    | "/dashboard/sign-in"
    | "/dashboard/sign-up"
    | "/dashboard"
    | "/dashboard/users/$user_id"
    | "/dashboard/users"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/$"
    | "/dashboard/$"
    | "/dashboard/settings"
    | "/dashboard/sign-in"
    | "/dashboard/sign-up"
    | "/dashboard"
    | "/dashboard/users/$user_id"
    | "/dashboard/users"
  id:
    | "__root__"
    | "/$"
    | "/dashboard/$"
    | "/dashboard/settings"
    | "/dashboard/sign-in"
    | "/dashboard/sign-up"
    | "/dashboard/"
    | "/dashboard/users/$user_id"
    | "/dashboard/users/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  DashboardSplatRoute: typeof DashboardSplatRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSignInRoute: typeof DashboardSignInRoute
  DashboardSignUpRoute: typeof DashboardSignUpRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUsersUseridRoute: typeof DashboardUsersUseridRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  DashboardSplatRoute: DashboardSplatRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSignInRoute: DashboardSignInRoute,
  DashboardSignUpRoute: DashboardSignUpRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUsersUseridRoute: DashboardUsersUseridRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$",
        "/dashboard/$",
        "/dashboard/settings",
        "/dashboard/sign-in",
        "/dashboard/sign-up",
        "/dashboard/",
        "/dashboard/users/$user_id",
        "/dashboard/users/"
      ]
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/dashboard/$": {
      "filePath": "dashboard/$.tsx"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx"
    },
    "/dashboard/sign-in": {
      "filePath": "dashboard/sign-in.tsx"
    },
    "/dashboard/sign-up": {
      "filePath": "dashboard/sign-up.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/dashboard/users/$user_id": {
      "filePath": "dashboard/users/$user_id.tsx"
    },
    "/dashboard/users/": {
      "filePath": "dashboard/users/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
